// Three illustrative datasets for /reports. Aurora Aesthetics — Singapore medspa.
// All monetary values are in DOLLARS (matches the backend), not cents.

import {
  type ReportDataV1,
  type ReportWindow,
  type PaidVisitRow,
  REPORT_WINDOWS,
  DEFAULT_REPORT_WINDOW,
} from "@switchboard/schemas";

export type { ReportDataV1 as ReportData, ReportWindow } from "@switchboard/schemas";
export type {
  Delta,
  DeltaKind,
  PullQuoteCopy,
  AttributionCell,
  AttributionData,
  FunnelRowData,
  FunnelNarrative,
  CampaignRow,
  ReportCampaignInsight,
  CostBreakdown,
  ManagedComparisonData,
  ManagedComparisonPair,
  ManagedComparisonMetrics,
  ManagedComparisonSource,
} from "@switchboard/schemas";

export { REPORT_WINDOWS, DEFAULT_REPORT_WINDOW };

// ─── THIS MONTH — goodFixture (showcase, populated managedComparison) ──
export const goodFixture: ReportDataV1 = {
  label: "THIS MONTH",
  period: "APR 1 — APR 30",
  dateFolio: "APR 1 — APR 30",
  pullquote: {
    pre: "Your team earned you ",
    value: "S$14,720",
    mid: " in attributed pipeline this month against ",
    cost: "S$612",
    post: " paid. Riley caught the creative-fatigue dip on Apr 8 before it cost you a weekend; Alex pulled three replies back from cold.",
  },
  attribution: {
    total: 14720,
    delta: { kind: "pos", text: "↑ 22% vs Mar" },
    riley: { value: 9180, caption: "ad-driven leads converted" },
    alex: { value: 5540, caption: "reply conversions" },
  },
  funnel: [
    { stage: "Impressions", n: 342000, label: "342k", delta: { kind: "pos", text: "↑ 8%" } },
    { stage: "Clicks", n: 4182, label: "4,182", delta: { kind: "pos", text: "↑ 3%" } },
    { stage: "Landing visits", n: 3896, label: "3,896", delta: { kind: "flat", text: "—" } },
    { stage: "Leads", n: 247, label: "247", delta: { kind: "pos", text: "↑ 14%" } },
    { stage: "Bookings", n: 47, label: "47", delta: { kind: "pos", text: "↑ 9%" } },
  ],
  funnelNarrative: {
    marker: "Riley · Apr 22",
    text: "CTR is sitting above the medspa benchmark of 1.1%. Spring-Hydrafacial is doing most of the lift; Q2-Lookalikes is dragging the average and probably wants pausing or fresh creative.",
  },
  campaigns: [
    {
      name: "Spring-Hydrafacial",
      spend: 620,
      impressions: 138400,
      inlineLinkClicks: 1842,
      costPerInlineLinkClick: 0.34,
      inlineLinkClickCtr: 0.0133,
      leads: 88,
      revenue: 6240,
      cpl: 7.05,
      clickToLeadRate: 0.0478,
      roas: 10.06,
    },
    {
      name: "Botox-Touchup-Q2",
      spend: 410,
      impressions: 76200,
      inlineLinkClicks: 982,
      costPerInlineLinkClick: 0.42,
      inlineLinkClickCtr: 0.0129,
      leads: 41,
      revenue: 2890,
      cpl: 10.0,
      clickToLeadRate: 0.0418,
      roas: 7.05,
    },
    {
      name: "Retargeting-30d",
      spend: 217,
      impressions: 41800,
      inlineLinkClicks: 612,
      costPerInlineLinkClick: 0.35,
      inlineLinkClickCtr: 0.0146,
      leads: 58,
      revenue: 3420,
      cpl: 3.74,
      clickToLeadRate: 0.0948,
      roas: 15.76,
    },
    {
      name: "Skin-Booster-Search",
      spend: 168,
      impressions: 22900,
      inlineLinkClicks: 384,
      costPerInlineLinkClick: 0.44,
      inlineLinkClickCtr: 0.0168,
      leads: 28,
      revenue: 1980,
      cpl: 6.0,
      clickToLeadRate: 0.0729,
      roas: 11.79,
    },
    {
      name: "Lookalike-Q2-Wide",
      spend: 412,
      impressions: 58900,
      inlineLinkClicks: 318,
      costPerInlineLinkClick: 1.3,
      inlineLinkClickCtr: 0.0054,
      leads: 9,
      revenue: 190,
      cpl: 45.78,
      clickToLeadRate: 0.0283,
      roas: 0.46,
    },
    {
      name: "TikTok-Discovery",
      spend: 285,
      impressions: 81400,
      inlineLinkClicks: 442,
      costPerInlineLinkClick: 0.64,
      inlineLinkClickCtr: 0.0054,
      leads: 6,
      revenue: 0,
      cpl: null,
      clickToLeadRate: 0.0136,
      roas: 0.0,
    },
  ],
  cost: { paid: 612, alt: 8000, saving: 7388 },
  heldRate: { attended: 38, matured: 45, rate: 38 / 45 },
  consentCompleteness: { validConsent: 42, bookable: 45, rate: 42 / 45 },
  receiptedBookings: { count: 41 },
  receiptedBookingQuality: {
    cohortSize: 41,
    confidence: { deterministic: 18, high: 12, medium: 7, low: 3, unattributed: 1 },
    exceptions: {
      missing_source: 1,
      missing_consent: 2,
      manual_override: 0,
      duplicate_contact_risk: 1,
    },
    bookingsNeedingAttention: 4,
  },
  costNarrative:
    "vs. an SDR at ~S$5,000/month plus a small ad-agency retainer at ~S$3,000. Your team replaces both, and they're on duty after hours.",
  managedComparison: {
    source: "in-period-cohort",
    ads: {
      managed: { spend: 2112, revenue: 14720, roas: 6.97 },
      unmanaged: { spend: 1840, revenue: 6420, roas: 3.49 },
      delta: { kind: "pos", text: "↑ 99% roas" },
    },
    conversations: {
      managed: { spend: 0, replies: 312, conversionRate: 0.221, replyMinutesP50: 4 },
      unmanaged: { spend: 0, replies: 156, conversionRate: 0.092, replyMinutesP50: 47 },
      delta: { kind: "pos", text: "↑ 140% conv" },
    },
  },
};

// ─── THIS WEEK — quietFixture (low numbers, flat, managedComparison null) ──
export const quietFixture: ReportDataV1 = {
  label: "THIS WEEK",
  period: "APR 27 — MAY 3",
  dateFolio: "APR 27 — MAY 3",
  pullquote: {
    pre: "Quieter week — ",
    value: "S$3,184",
    mid: " of attributed pipeline against ",
    cost: "S$142",
    post: " paid. Mostly Spring-Hydrafacial. Worth a call about whether to scale into Mother's Day or hold flat.",
  },
  attribution: {
    total: 3184,
    delta: { kind: "flat", text: "— flat WoW" },
    riley: { value: 2104, caption: "ad-driven leads converted" },
    alex: { value: 1080, caption: "reply conversions" },
  },
  funnel: [
    { stage: "Impressions", n: 78400, label: "78k", delta: null },
    { stage: "Clicks", n: 924, label: "924", delta: null },
    { stage: "Landing visits", n: 871, label: "871", delta: null },
    { stage: "Leads", n: 54, label: "54", delta: { kind: "flat", text: "—" } },
    { stage: "Bookings", n: 9, label: "9", delta: { kind: "flat", text: "—" } },
  ],
  funnelNarrative: {
    marker: "Riley · Apr 30",
    text: "Volume is light because we paused TikTok-Discovery on Tuesday. CTR and conversion shape both look healthy underneath — this isn't a soft week, it's a smaller week.",
  },
  campaigns: [
    {
      name: "Spring-Hydrafacial",
      spend: 142,
      impressions: 31200,
      inlineLinkClicks: 412,
      costPerInlineLinkClick: 0.34,
      inlineLinkClickCtr: 0.0132,
      leads: 22,
      revenue: 1560,
      cpl: 6.45,
      clickToLeadRate: 0.0534,
      roas: 10.99,
    },
    {
      name: "Retargeting-30d",
      spend: 58,
      impressions: 9400,
      inlineLinkClicks: 138,
      costPerInlineLinkClick: 0.42,
      inlineLinkClickCtr: 0.0147,
      leads: 13,
      revenue: 820,
      cpl: 4.46,
      clickToLeadRate: 0.0942,
      roas: 14.14,
    },
    {
      name: "Botox-Touchup-Q2",
      spend: 94,
      impressions: 17800,
      inlineLinkClicks: 224,
      costPerInlineLinkClick: 0.42,
      inlineLinkClickCtr: 0.0126,
      leads: 8,
      revenue: 584,
      cpl: 11.75,
      clickToLeadRate: 0.0357,
      roas: 6.21,
    },
    {
      name: "Skin-Booster-Search",
      spend: 41,
      impressions: 4900,
      inlineLinkClicks: 86,
      costPerInlineLinkClick: 0.48,
      inlineLinkClickCtr: 0.0176,
      leads: 5,
      revenue: 220,
      cpl: 8.2,
      clickToLeadRate: 0.0581,
      roas: 5.37,
    },
  ],
  cost: { paid: 142, alt: 1846, saving: 1704 },
  heldRate: { attended: 0, matured: 0, rate: null },
  consentCompleteness: { validConsent: 0, bookable: 0, rate: null },
  receiptedBookings: { count: 0 },
  receiptedBookingQuality: {
    cohortSize: 0,
    confidence: { deterministic: 0, high: 0, medium: 0, low: 0, unattributed: 0 },
    exceptions: {
      missing_source: 0,
      missing_consent: 0,
      manual_override: 0,
      duplicate_contact_risk: 0,
    },
    bookingsNeedingAttention: 0,
  },
  costNarrative:
    "vs. an SDR + agency retainer pro-rated weekly. Even at low volume the base cost is a small fraction.",
  managedComparison: null,
};

// ─── THIS QUARTER — problemFixture (negative delta, populated managedComparison) ──
export const problemFixture: ReportDataV1 = {
  label: "THIS QUARTER",
  period: "FEB 1 — APR 30",
  dateFolio: "FEB 1 — APR 30",
  pullquote: {
    pre: "Mixed quarter — ",
    value: "S$28,402",
    mid: " attributed against ",
    cost: "S$1,343",
    post: ". February was strong; March slipped on creative fatigue. Riley flagged it on Mar 14 and we recovered through April.",
  },
  attribution: {
    total: 28402,
    delta: { kind: "neg", text: "↓ 6% vs Q1" },
    riley: { value: 18620, caption: "ad-driven leads converted" },
    alex: { value: 9782, caption: "reply conversions" },
  },
  funnel: [
    { stage: "Impressions", n: 1020000, label: "1.02m", delta: { kind: "pos", text: "↑ 4%" } },
    { stage: "Clicks", n: 11842, label: "11.8k", delta: { kind: "neg", text: "↓ 9%" } },
    { stage: "Landing visits", n: 10948, label: "10.9k", delta: null },
    { stage: "Leads", n: 612, label: "612", delta: { kind: "neg", text: "↓ 12%" } },
    { stage: "Bookings", n: 118, label: "118", delta: { kind: "neg", text: "↓ 8%" } },
  ],
  funnelNarrative: {
    marker: "Riley · Mar 14",
    text: "Friction between clicks and leads. CTR was holding but conversion dropped — read as creative fatigue on the March wave. New Hydrafacial set went live Mar 22 and the rate came back.",
  },
  campaigns: [
    {
      name: "Spring-Hydrafacial",
      spend: 1820,
      impressions: 412000,
      inlineLinkClicks: 5482,
      costPerInlineLinkClick: 0.33,
      inlineLinkClickCtr: 0.0133,
      leads: 238,
      revenue: 16880,
      cpl: 7.65,
      clickToLeadRate: 0.0434,
      roas: 9.27,
    },
    {
      name: "Botox-Touchup-Q1",
      spend: 1240,
      impressions: 198000,
      inlineLinkClicks: 2412,
      costPerInlineLinkClick: 0.51,
      inlineLinkClickCtr: 0.0122,
      leads: 86,
      revenue: 6080,
      cpl: 14.42,
      clickToLeadRate: 0.0356,
      roas: 4.9,
    },
    {
      name: "Retargeting-30d",
      spend: 651,
      impressions: 122000,
      inlineLinkClicks: 1812,
      costPerInlineLinkClick: 0.36,
      inlineLinkClickCtr: 0.0149,
      leads: 142,
      revenue: 3920,
      cpl: 4.58,
      clickToLeadRate: 0.0784,
      roas: 6.02,
    },
    {
      name: "Skin-Booster-Search",
      spend: 504,
      impressions: 68400,
      inlineLinkClicks: 1142,
      costPerInlineLinkClick: 0.44,
      inlineLinkClickCtr: 0.0167,
      leads: 84,
      revenue: 1390,
      cpl: 6.0,
      clickToLeadRate: 0.0735,
      roas: 2.76,
    },
    {
      name: "Lookalike-Q2-Wide",
      spend: 285,
      impressions: 41200,
      inlineLinkClicks: 218,
      costPerInlineLinkClick: 1.31,
      inlineLinkClickCtr: 0.0053,
      leads: 12,
      revenue: 180,
      cpl: 23.75,
      clickToLeadRate: 0.055,
      roas: 0.63,
    },
    {
      name: "TikTok-Discovery",
      spend: 412,
      impressions: 178400,
      inlineLinkClicks: 776,
      costPerInlineLinkClick: 0.53,
      inlineLinkClickCtr: 0.0044,
      leads: 28,
      revenue: 0,
      cpl: null,
      clickToLeadRate: 0.0361,
      roas: 0.0,
    },
    {
      name: "Mar-Creative-Test",
      spend: 248,
      impressions: 38800,
      inlineLinkClicks: 0,
      costPerInlineLinkClick: 0,
      inlineLinkClickCtr: 0,
      leads: 0,
      revenue: 0,
      cpl: null,
      clickToLeadRate: null,
      roas: 0.0,
    },
  ],
  cost: { paid: 1343, alt: 24000, saving: 22657 },
  heldRate: { attended: 71, matured: 118, rate: 71 / 118 },
  consentCompleteness: { validConsent: 64, bookable: 118, rate: 64 / 118 },
  receiptedBookings: { count: 112 },
  receiptedBookingQuality: {
    cohortSize: 112,
    confidence: { deterministic: 20, high: 18, medium: 30, low: 28, unattributed: 16 },
    exceptions: {
      missing_source: 16,
      missing_consent: 14,
      manual_override: 2,
      duplicate_contact_risk: 5,
    },
    bookingsNeedingAttention: 33,
  },
  costNarrative:
    "vs. SDR + agency retainer across three months. Even in a soft quarter the price gap is roughly one-eighteenth.",
  managedComparison: {
    source: "in-period-cohort",
    ads: {
      managed: { spend: 5160, revenue: 28402, roas: 5.5 },
      unmanaged: { spend: 4280, revenue: 12180, roas: 2.85 },
      delta: { kind: "pos", text: "↑ 93% roas" },
    },
    conversations: {
      managed: { spend: 0, replies: 842, conversionRate: 0.186, replyMinutesP50: 6 },
      unmanaged: { spend: 0, replies: 412, conversionRate: 0.078, replyMinutesP50: 62 },
      delta: { kind: "pos", text: "↑ 138% conv" },
    },
  },
};

export const FIXTURES_BY_WINDOW: Record<ReportWindow, ReportDataV1> = {
  "THIS WEEK": quietFixture,
  "THIS MONTH": goodFixture,
  "THIS QUARTER": problemFixture,
};

// ─── Paid-visits fixture — Aurora Aesthetics, SGD amounts in major units ────
// Two CTWA-captured rows with real campaign names; one campaign_missing row.
export const PAID_VISITS_FIXTURE: PaidVisitRow[] = [
  {
    bookingId: "bk-aurora-001",
    amountMajor: 250,
    currency: "SGD",
    campaignId: "spring-hydrafacial",
    campaignName: "Botox Awareness — CTWA",
    attributionBasis: "ctwa_captured",
    paidAt: "2026-06-01T10:30:00.000Z",
  },
  {
    bookingId: "bk-aurora-002",
    amountMajor: 480.5,
    currency: "SGD",
    campaignId: "filler-retargeting",
    campaignName: "Filler Retargeting",
    attributionBasis: "ctwa_captured",
    paidAt: "2026-06-03T14:15:00.000Z",
  },
  {
    bookingId: "bk-aurora-003",
    amountMajor: 180,
    currency: "SGD",
    campaignId: null,
    campaignName: null,
    attributionBasis: "campaign_missing",
    paidAt: "2026-06-04T09:00:00.000Z",
  },
];
