// ---------------------------------------------------------------------------
// Campaign Plan Schema — structured output from the Strategist Agent
// ---------------------------------------------------------------------------
// Defines the shape of a campaign plan that the Strategist produces.
// Plans go through governance approval before execution.
// ---------------------------------------------------------------------------

import { z } from "zod";

// ---------------------------------------------------------------------------
// Sub-schemas
// ---------------------------------------------------------------------------

export const FunnelModeSchema = z.enum(["lead_gen", "conversions", "awareness"]);
export type FunnelMode = z.infer<typeof FunnelModeSchema>;

export const AdCreativeDirectionSchema = z.object({
  /** Creative format type. */
  type: z.enum(["image", "video", "carousel"]),
  /** Whether the creative is user-provided or AI-generated. */
  source: z.enum(["provided", "generated", "stock"]),
  /** URL to existing creative asset (when source = "provided"). */
  url: z.string().url().optional(),
  /** Suggested headline text. */
  headline: z.string().min(1),
  /** Suggested body/primary text. */
  body: z.string().min(1),
  /** Call-to-action label. */
  cta: z.string().min(1),
  /** Where the ad sends traffic. */
  destinationType: z.enum(["lead_form", "telegram_bot", "website", "messenger"]),
});
export type AdCreativeDirection = z.infer<typeof AdCreativeDirectionSchema>;

export const TargetingSpecSchema = z.object({
  /** Geographic targeting. */
  location: z.string().min(1),
  /** Age range (e.g. "25-54"). */
  ageRange: z.string().optional(),
  /** Interest-based targeting keywords. */
  interests: z.array(z.string()).optional(),
  /** Audience exclusions. */
  exclusions: z.array(z.string()).optional(),
  /** Whether to use platform's automated audience expansion. */
  advantagePlusAudience: z.boolean().optional(),
});
export type TargetingSpec = z.infer<typeof TargetingSpecSchema>;

export const PlannedAdSetSchema = z.object({
  /** Ad set name. */
  name: z.string().min(1),
  /** Targeting configuration. */
  targeting: TargetingSpecSchema,
  /** Optimization goal (e.g. "LEAD_GENERATION", "CONVERSIONS"). */
  optimization: z.string().min(1),
  /** Optional flight schedule. */
  schedule: z
    .object({
      start: z.string(),
      end: z.string(),
    })
    .optional(),
});
export type PlannedAdSet = z.infer<typeof PlannedAdSetSchema>;

export const PlannedCampaignSchema = z.object({
  /** Campaign name. */
  name: z.string().min(1),
  /** Daily budget in dollars. */
  dailyBudget: z.number().positive(),
  /** Campaign objective. */
  objective: z.string().min(1),
  /** Bid strategy recommendation. */
  bidStrategy: z.string().optional(),
  /** Ad sets within this campaign. */
  adSets: z.array(PlannedAdSetSchema).min(1),
  /** Ad creative directions. */
  ads: z.array(AdCreativeDirectionSchema).min(1),
});
export type PlannedCampaign = z.infer<typeof PlannedCampaignSchema>;

export const EstimatedMetricsSchema = z.object({
  /** Estimated cost per lead/acquisition. */
  cpl: z.number().nonnegative().optional(),
  /** Estimated cost per action/conversion. */
  cpa: z.number().nonnegative().optional(),
  /** Estimated monthly reach. */
  reach: z.number().nonnegative().optional(),
  /** Estimated monthly impressions. */
  impressions: z.number().nonnegative().optional(),
  /** Estimated monthly conversions/leads. */
  conversions: z.number().nonnegative().optional(),
});
export type EstimatedMetrics = z.infer<typeof EstimatedMetricsSchema>;

// ---------------------------------------------------------------------------
// Root Schema
// ---------------------------------------------------------------------------

export const CampaignPlanSchema = z.object({
  /** Unique plan ID (generated by strategist). */
  id: z.string().min(1),
  /** Human-readable plan name. */
  name: z.string().min(1),
  /** High-level funnel objective. */
  funnelMode: FunnelModeSchema,
  /** Total monthly budget in dollars. */
  monthlyBudget: z.number().positive(),
  /** Individual campaigns in this plan. */
  campaigns: z.array(PlannedCampaignSchema).min(1),
  /** Estimated performance metrics. */
  estimatedMetrics: EstimatedMetricsSchema,
  /** Why this plan was recommended (strategist reasoning). */
  rationale: z.string().min(1),
  /** Business vertical context (e.g. "clinic", "commerce"). */
  vertical: z.string().optional(),
  /** Timestamp when the plan was generated. */
  createdAt: z.string(),
});
export type CampaignPlan = z.infer<typeof CampaignPlanSchema>;
