import type { AuditEntryBrowseRow } from "@switchboard/schemas";

/**
 * Raw sketches for the /activity v2 fixture distribution. Split out from
 * fixtures.ts so the projection logic and the data table stay under the
 * 600-line architecture-check limit (CLAUDE.md). Consumed only by
 * fixtures.ts — do not import elsewhere.
 *
 * See fixtures.ts top comment for the distribution invariants this set
 * is designed to satisfy.
 */

export interface Sketch {
  ago: number;
  id: string;
  eventType: AuditEntryBrowseRow["eventType"];
  actorType: AuditEntryBrowseRow["actorType"];
  actorId: string;
  entityType: string;
  entityId: string;
  risk: AuditEntryBrowseRow["riskCategory"];
  vis: AuditEntryBrowseRow["visibilityLevel"];
  summary: string;
  snapshotKeys: string[];
  redacted: number;
  evidence: Array<{ type: "inline" | "pointer"; seed: string }>;
  envelope: string | null;
  trace: string | null;
}

// Time-unit ladder used inside the SKETCHES literals below. fixtures.ts owns
// the NOW anchor and `iso(ago)` projection — these constants stay local here
// so the literals remain readable.
const m = 60_000;
const h = 60 * m;
const d = 24 * h;

export const SKETCHES: Sketch[] = [
  // ── Recent: action lifecycle + agent control ────────────────────────
  {
    ago: 4 * m + 22_000,
    id: "audit_a1k2m3p9",
    eventType: "action.executed",
    actorType: "agent",
    actorId: "agent_alex_001",
    entityType: "calendar_event",
    entityId: "cal_evt_99214",
    risk: "low",
    vis: "org",
    summary:
      "Booked HydraFacial consult for contact CTC:7b2e94c1 in calendar 'Operations' at 2026-05-10 09:00 SGT",
    snapshotKeys: [
      "actionType",
      "decisionId",
      "targetEntityType",
      "targetEntityId",
      "correlationId",
    ],
    redacted: 0,
    evidence: [{ type: "pointer", seed: "evx_cal_evt_99214" }],
    envelope: "env_2f1a08c4",
    trace: "trace_a1k2m3p9",
  },
  {
    ago: 11 * m + 4_000,
    id: "audit_b2l3n4q0",
    eventType: "action.approved",
    actorType: "user",
    actorId: "user_kim_principal",
    entityType: "approval_envelope",
    entityId: "env_2f1a08c4",
    risk: "critical",
    vis: "org",
    summary:
      "Operator signed refund of SGD 4,820 to client #SG-44120 (adverse reaction — HydraFacial)",
    snapshotKeys: ["actionType", "approvalId", "decisionId", "envelopeId", "correlationId"],
    redacted: 5,
    evidence: [
      { type: "pointer", seed: "evx_apr_2f1a08_pol" },
      { type: "inline", seed: "evx_apr_2f1a08_sig" },
    ],
    envelope: "env_2f1a08c4",
    trace: "trace_b2l3n4q0",
  },
  {
    ago: 17 * m + 41_000,
    id: "audit_c3m4o5r1",
    eventType: "action.rejected",
    actorType: "user",
    actorId: "user_kim_principal",
    entityType: "recommendation",
    entityId: "rec_adspend_887",
    risk: "medium",
    vis: "org",
    summary: "Operator rejected ad-spend increase from SGD 320/day → 480/day (rec_adspend_887)",
    snapshotKeys: ["actionType", "recommendationId", "decisionId"],
    redacted: 0,
    evidence: [],
    envelope: "env_adspend_887",
    trace: null,
  },
  {
    ago: 23 * m,
    id: "audit_d4n5p6s2",
    eventType: "action.failed",
    actorType: "agent",
    actorId: "agent_alex_001",
    entityType: "stripe_payment",
    entityId: "pi_3O1nKx2qF8sg",
    risk: "high",
    vis: "org",
    summary: "Refund execution failed — Stripe returned 503 after 2 retries; envelope intact",
    snapshotKeys: ["actionType", "approvalId", "correlationId", "traceId"],
    redacted: 0,
    evidence: [{ type: "inline", seed: "evx_pi_3O1nKx2qF8sg_err" }],
    envelope: "env_2f1a08c4",
    trace: "trace_d4n5p6s2",
  },
  {
    ago: 38 * m + 6_000,
    id: "audit_e5o6q7t3",
    eventType: "action.evaluated",
    actorType: "agent",
    actorId: "agent_alex_001",
    entityType: "action_proposal",
    entityId: "act_pro_e5o6q7t3",
    risk: "low",
    vis: "org",
    summary:
      "Alex evaluated refund proposal against spend policy (passed) and quorum policy (1-of-1)",
    snapshotKeys: ["actionType", "decisionId", "approvalId"],
    redacted: 0,
    evidence: [],
    envelope: "env_2f1a08c4",
    trace: "trace_e5o6q7t3",
  },
  {
    ago: 52 * m,
    id: "audit_f6p7r8u4",
    eventType: "agent.emergency-halted",
    actorType: "user",
    actorId: "user_kim_principal",
    entityType: "agent",
    entityId: "agent_riley_002",
    risk: "high",
    vis: "org",
    summary: "Riley emergency-halted by operator after duplicate booking event surge",
    snapshotKeys: ["agentKey", "correlationId"],
    redacted: 0,
    evidence: [{ type: "inline", seed: "evx_riley_halt_witness" }],
    envelope: null,
    trace: "trace_f6p7r8u4",
  },
  {
    ago: 1 * h + 14 * m,
    id: "audit_g7q8s9v5",
    eventType: "policy.updated",
    actorType: "user",
    actorId: "user_ops_lead",
    entityType: "spend_policy",
    entityId: "policy_spend_001",
    risk: "medium",
    vis: "org",
    summary: "Daily ad-spend cap raised from SGD 500 → SGD 750 (effective 2026-05-09)",
    snapshotKeys: ["id", "kind", "source"],
    redacted: 0,
    evidence: [],
    envelope: null,
    trace: null,
  },
  {
    ago: 1 * h + 47 * m,
    id: "audit_h8r9t0w6",
    eventType: "connection.degraded",
    actorType: "system",
    actorId: "system_monitor",
    entityType: "connection",
    entityId: "conn_meta_ads_001",
    risk: "medium",
    vis: "org",
    summary: "Meta Ads token nearing expiry — 6h 12m until refresh window closes",
    snapshotKeys: ["id", "source"],
    redacted: 0,
    evidence: [{ type: "inline", seed: "evx_conn_meta_ads_001" }],
    envelope: null,
    trace: null,
  },
  {
    ago: 2 * h + 9 * m,
    id: "audit_i9s0u1x7",
    eventType: "action.queued",
    actorType: "agent",
    actorId: "agent_riley_002",
    entityType: "sms_broadcast",
    entityId: "sms_brd_2026_05_09",
    risk: "medium",
    vis: "org",
    summary: "Riley queued SMS broadcast to 1,284 SG numbers awaiting 2-of-3 quorum",
    snapshotKeys: ["actionType", "approvalId", "envelopeId", "correlationId"],
    redacted: 0,
    evidence: [{ type: "pointer", seed: "evx_sms_brd_target_set" }],
    envelope: "env_9b73c1ee",
    trace: "trace_i9s0u1x7",
  },
  {
    ago: 2 * h + 11 * m,
    id: "audit_j0t1v2y8",
    eventType: "action.snapshot",
    actorType: "agent",
    actorId: "agent_riley_002",
    entityType: "sms_broadcast",
    entityId: "sms_brd_2026_05_09",
    risk: "low",
    vis: "org",
    summary: "Pre-execution parameter snapshot taken — target set frozen at 1,284 numbers",
    snapshotKeys: ["actionType", "decisionId", "correlationId"],
    redacted: 0,
    evidence: [{ type: "pointer", seed: "evx_sms_brd_snap" }],
    envelope: "env_9b73c1ee",
    trace: "trace_j0t1v2y8",
  },
  // ── Identity & governance ──────────────────────────────────────────
  {
    ago: 3 * h + 2 * m,
    id: "audit_k1u2w3z9",
    eventType: "work_trace.integrity_override",
    actorType: "user",
    actorId: "user_ops_lead",
    entityType: "work_trace",
    entityId: "wt_act_4n0pz1qm",
    risk: "critical",
    vis: "org",
    summary:
      "Operator overrode integrity check on action act_4n0pz1qm (stale snapshot; replay safe)",
    snapshotKeys: ["id", "traceId", "correlationId"],
    redacted: 7,
    evidence: [
      { type: "pointer", seed: "evx_wt_override_witness_1" },
      { type: "pointer", seed: "evx_wt_override_witness_2" },
    ],
    envelope: null,
    trace: "trace_k1u2w3z9",
  },
  {
    ago: 4 * h + 18 * m,
    id: "audit_l2v3x4a0",
    eventType: "competence.promoted",
    actorType: "user",
    actorId: "user_kim_principal",
    entityType: "agent",
    entityId: "agent_alex_001",
    risk: "low",
    vis: "org",
    summary: "Alex promoted to autonomous calendar booking (consults ≤ 60min, business hours)",
    snapshotKeys: ["agentKey", "targetEntityType", "targetEntityId"],
    redacted: 0,
    evidence: [],
    envelope: null,
    trace: null,
  },
  {
    ago: 5 * h + 7 * m,
    id: "audit_m3w4y5b1",
    eventType: "connection.established",
    actorType: "user",
    actorId: "user_kim_principal",
    entityType: "connection",
    entityId: "conn_stripe_sgd",
    risk: "low",
    vis: "org",
    summary: "Stripe SGD connector linked — refunds and charges authorized scope",
    snapshotKeys: ["id", "source", "kind"],
    redacted: 0,
    evidence: [{ type: "inline", seed: "evx_conn_stripe_sgd" }],
    envelope: null,
    trace: null,
  },
  {
    ago: 6 * h + 33 * m,
    id: "audit_n4x5z6c2",
    eventType: "agent.resumed",
    actorType: "user",
    actorId: "user_kim_principal",
    entityType: "agent",
    entityId: "agent_riley_002",
    risk: "none",
    vis: "org",
    summary: "Riley resumed after operator verified upstream event de-duplication is in place",
    snapshotKeys: ["agentKey"],
    redacted: 0,
    evidence: [],
    envelope: null,
    trace: null,
  },
  {
    ago: 8 * h + 12 * m,
    id: "audit_o5y6a7d3",
    eventType: "action.undo_requested",
    actorType: "user",
    actorId: "user_kim_principal",
    entityType: "calendar_event",
    entityId: "cal_evt_99188",
    risk: "low",
    vis: "org",
    summary: "Operator requested undo of duplicate booking cal_evt_99188 (90s window open)",
    snapshotKeys: ["actionType", "decisionId", "correlationId"],
    redacted: 0,
    evidence: [],
    envelope: null,
    trace: "trace_o5y6a7d3",
  },
  {
    ago: 8 * h + 12 * m + 47_000,
    id: "audit_p6z7b8e4",
    eventType: "action.undo_executed",
    actorType: "agent",
    actorId: "agent_alex_001",
    entityType: "calendar_event",
    entityId: "cal_evt_99188",
    risk: "low",
    vis: "org",
    summary: "Alex executed undo on cal_evt_99188 — Cal.com returned 200, slot released",
    snapshotKeys: ["actionType", "decisionId", "correlationId"],
    redacted: 0,
    evidence: [{ type: "inline", seed: "evx_undo_99188" }],
    envelope: null,
    trace: "trace_p6z7b8e4",
  },
  {
    ago: 10 * h,
    id: "audit_q7a8c9f5",
    eventType: "policy.created",
    actorType: "user",
    actorId: "user_ops_lead",
    entityType: "approval_policy",
    entityId: "policy_refund_quorum",
    risk: "medium",
    vis: "org",
    summary:
      "Created approval policy: refunds ≥ SGD 2,500 require 2-of-3 quorum (principal, ops, finance)",
    snapshotKeys: ["id", "kind"],
    redacted: 0,
    evidence: [],
    envelope: null,
    trace: null,
  },
  {
    ago: 14 * h + 4 * m,
    id: "audit_r8b9d0g6",
    eventType: "identity.updated",
    actorType: "service_account",
    actorId: "svc_directory_sync",
    entityType: "identity",
    entityId: "identity_user_kim",
    risk: "none",
    vis: "public",
    summary: "Directory sync updated display name for user_kim_principal (Workday → Switchboard)",
    snapshotKeys: ["id", "kind"],
    redacted: 0,
    evidence: [{ type: "inline", seed: "evx_dirsync_kim" }],
    envelope: null,
    trace: null,
  },
  {
    ago: 16 * h + 52 * m,
    id: "audit_s9c0e1h7",
    eventType: "overlay.activated",
    actorType: "user",
    actorId: "user_ops_lead",
    entityType: "overlay",
    entityId: "overlay_maintenance_01",
    risk: "low",
    vis: "org",
    summary: "Maintenance overlay activated — autonomous agent execution paused org-wide for 30m",
    snapshotKeys: ["id", "kind", "source"],
    redacted: 0,
    evidence: [],
    envelope: null,
    trace: null,
  },
  {
    ago: 18 * h + 6 * m,
    id: "audit_t0d1f2i8",
    eventType: "overlay.deactivated",
    actorType: "user",
    actorId: "user_ops_lead",
    entityType: "overlay",
    entityId: "overlay_maintenance_01",
    risk: "none",
    vis: "org",
    summary: "Maintenance overlay deactivated — autonomous execution resumed",
    snapshotKeys: ["id", "kind"],
    redacted: 0,
    evidence: [],
    envelope: null,
    trace: null,
  },
  {
    ago: 20 * h + 41 * m,
    id: "audit_u1e2g3j9",
    eventType: "agent.activated",
    actorType: "user",
    actorId: "user_kim_principal",
    entityType: "agent",
    entityId: "agent_alex_001",
    risk: "none",
    vis: "org",
    summary: "Alex activated for Aurora Aesthetics org",
    snapshotKeys: ["agentKey"],
    redacted: 0,
    evidence: [],
    envelope: null,
    trace: null,
  },
  {
    ago: 1 * d + 2 * h,
    id: "audit_v2f3h4k0",
    eventType: "action.denied",
    actorType: "service_account",
    actorId: "svc_policy_engine",
    entityType: "action_proposal",
    entityId: "act_pro_v2f3h4k0",
    risk: "low",
    vis: "org",
    summary: "Policy engine denied auto-charge SGD 1,290 — agent below required competence tier",
    snapshotKeys: ["actionType", "decisionId"],
    redacted: 0,
    evidence: [{ type: "inline", seed: "evx_denied_act_v2" }],
    envelope: null,
    trace: null,
  },
  {
    ago: 1 * d + 8 * h,
    id: "audit_w3g4i5l1",
    eventType: "action.approval_expired",
    actorType: "system",
    actorId: "system_scheduler",
    entityType: "approval_envelope",
    entityId: "env_4e082a55",
    risk: "low",
    vis: "org",
    summary: "Approval window expired without quorum — DB rotation envelope env_4e082a55 voided",
    snapshotKeys: ["actionType", "envelopeId", "approvalId"],
    redacted: 0,
    evidence: [],
    envelope: "env_4e082a55",
    trace: null,
  },
  {
    ago: 1 * d + 14 * h,
    id: "audit_x4h5j6m2",
    eventType: "action.cancelled",
    actorType: "user",
    actorId: "user_kim_principal",
    entityType: "action_proposal",
    entityId: "act_pro_x4h5j6m2",
    risk: "low",
    vis: "org",
    summary: "Operator cancelled proposed bulk-archive of 412 dormant contacts before evaluation",
    snapshotKeys: ["actionType", "decisionId"],
    redacted: 0,
    evidence: [],
    envelope: null,
    trace: null,
  },
  {
    ago: 2 * d + 1 * h,
    id: "audit_y5i6k7n3",
    eventType: "competence.demoted",
    actorType: "user",
    actorId: "user_kim_principal",
    entityType: "agent",
    entityId: "agent_riley_002",
    risk: "low",
    vis: "org",
    summary: "Riley demoted from autonomous broadcast — requires operator co-sign per send",
    snapshotKeys: ["agentKey", "targetEntityType"],
    redacted: 0,
    evidence: [],
    envelope: null,
    trace: null,
  },
  {
    ago: 2 * d + 11 * h,
    id: "audit_z6j7l8o4",
    eventType: "connection.revoked",
    actorType: "user",
    actorId: "user_kim_principal",
    entityType: "connection",
    entityId: "conn_twilio_legacy",
    risk: "medium",
    vis: "org",
    summary: "Twilio legacy connector revoked — superseded by conn_twilio_sg_2026",
    snapshotKeys: ["id", "source"],
    redacted: 0,
    evidence: [{ type: "inline", seed: "evx_conn_twilio_revoke" }],
    envelope: null,
    trace: null,
  },
  {
    ago: 3 * d + 4 * h,
    id: "audit_a7k8m9p5",
    eventType: "policy.deleted",
    actorType: "user",
    actorId: "user_ops_lead",
    entityType: "approval_policy",
    entityId: "policy_legacy_refund",
    risk: "medium",
    vis: "org",
    summary: "Legacy refund policy deleted — replaced by policy_refund_quorum",
    snapshotKeys: ["id", "kind"],
    redacted: 0,
    evidence: [],
    envelope: null,
    trace: null,
  },
  {
    ago: 4 * d + 6 * h,
    id: "audit_b8l9n0q6",
    eventType: "delegation.chain_resolved",
    actorType: "system",
    actorId: "system_delegation_resolver",
    entityType: "delegation",
    entityId: "del_kim_to_ops",
    risk: "none",
    vis: "org",
    summary: "Delegation chain resolved: user_kim_principal → user_ops_lead (out-of-office, 4d)",
    snapshotKeys: ["id", "source"],
    redacted: 0,
    evidence: [],
    envelope: null,
    trace: null,
  },
  {
    ago: 5 * d + 9 * h,
    id: "audit_c9m0o1r7",
    eventType: "entity.linked",
    actorType: "agent",
    actorId: "agent_alex_001",
    entityType: "contact",
    entityId: "CTC:7b2e94c1",
    risk: "low",
    vis: "org",
    summary: "Linked WhatsApp identity +65 8842 **** to contact CTC:7b2e94c1 via verified OTP",
    snapshotKeys: ["id", "source", "targetEntityType", "targetEntityId"],
    redacted: 0,
    evidence: [{ type: "inline", seed: "evx_link_ctc_7b2e94c1" }],
    envelope: null,
    trace: null,
  },
  // NON-operational — only visible under "All events"
  {
    ago: 6 * d + 12 * h,
    id: "audit_d0n1p2s8",
    eventType: "event.published",
    actorType: "system",
    actorId: "system_event_bus",
    entityType: "order",
    entityId: "order_88821",
    risk: "none",
    vis: "public",
    summary: "Event order.completed published to 4 subscribers (envelope env_order_88821)",
    snapshotKeys: ["id", "kind", "envelopeId"],
    redacted: 0,
    evidence: [],
    envelope: "env_order_88821",
    trace: null,
  },
];
