import type { DetailRow } from "./types";

const NOW = Date.now();
const MIN = 60_000;
const HR = 60 * MIN;
// `offset` is signed relative to NOW: negative = past, positive = future.
// (Sibling fixtures in activity/reports use `iso(ago)` subtraction — this
// file uses signed addition for clarity when mixing past `createdAt` and
// future `expiresAt` on the same row.)
const iso = (offset: number) => new Date(NOW + offset).toISOString();
const h = (s: string) => "0x" + s;

export const APPROVALS_FIXTURES: DetailRow[] = [
  {
    id: "apr_2f1a08",
    summary: "Refund SGD 4,820 to client #SG-44120 for adverse reaction during HydraFacial session",
    riskCategory: "critical",
    status: "pending",
    envelopeId: "env_2f1a08c4",
    expiresAt: iso(4 * MIN + 12_000),
    bindingHash: h("2f1a08c4e9b1d7a4f0c3b8a5d2e7f1a9"),
    createdAt: iso(-41 * MIN),
    agent: "billing-agent",
    requestedBy: "Billing",
    request: {
      action: "billing.refund.issue",
      parametersSnapshot: {
        accountId: "SG-44120",
        amount: 4820,
        currency: "SGD",
        reason: "adverse_reaction_treatment",
        rail: "stripe.refund",
        memo: "HydraFacial 2026-05-08 — adverse reaction, full refund per care policy",
      },
      approvers: ["p-1", "kira.l"],
      approvalsRequired: 2,
    },
    state: { approvalHashes: [], respondedBy: null, respondedAt: null },
  },
  {
    id: "apr_9b73c1",
    summary: "Send promo SMS (15% off May) to 4,208 lapsed clients — PDPA-opted-in, SG locale",
    riskCategory: "high",
    status: "pending",
    envelopeId: "env_9b73c1aa",
    expiresAt: iso(38 * MIN),
    bindingHash: h("9b73c1aa4f1d6c92e2a5b8d1f4c7e0a3"),
    createdAt: iso(-22 * MIN),
    agent: "growth-agent",
    requestedBy: "Growth",
    request: {
      action: "comms.sms.broadcast",
      parametersSnapshot: {
        channel: "sms.twilio",
        segment: "lapsed_90d_sg_pdpa_optin",
        recipients: 4208,
        copy: "Hi {first_name}, we miss you at Aurora. 15% off any treatment this May with MAY15. Reply STOP to opt out.",
        sendWindow: "Today 14:00–17:00 SGT",
        promoCode: "MAY15",
        estimatedCost: "SGD 252.48",
      },
      approvers: ["p-1", "kira.l", "marcus.t"],
      approvalsRequired: 3,
    },
    state: { approvalHashes: ["0xK1RA", "0xMARC"], respondedBy: null, respondedAt: null },
  },
  {
    id: "apr_d77c20",
    summary: "Apply 25% loyalty discount on Botox renewal · order #SG-44109",
    riskCategory: "medium",
    status: "pending",
    envelopeId: "env_d77c20b7",
    expiresAt: iso(42 * MIN),
    bindingHash: h("d77c20b73f6b9c2e5d8a1f4c7b0e3a6d"),
    createdAt: iso(-18 * MIN),
    agent: "support-agent",
    requestedBy: "Care",
    request: {
      action: "billing.discount.apply",
      parametersSnapshot: {
        orderId: "SG-44109",
        clientId: "SG-19224",
        clientTier: "platinum",
        treatment: "Botox renewal · forehead + glabella",
        basePriceSGD: 1280,
        discountPct: 10,
        memo: "Initial 10% per loyalty policy",
      },
      approvers: ["p-1"],
      approvalsRequired: 1,
    },
    patchProposal: {
      proposedBy: "p-1",
      proposedAt: iso(-2 * MIN),
      diff: {
        discountPct: 25,
        memo: "Customer churn-risk; tier exception applies. Bumping to 25% to retain.",
      },
    },
    state: { approvalHashes: [], respondedBy: null, respondedAt: null },
  },
  {
    id: "apr_4e082a",
    summary: "Rotate prod read-replica credentials · aurora-bookings-db",
    riskCategory: "high",
    status: "pending",
    envelopeId: "env_4e082afc",
    expiresAt: iso(51 * MIN),
    bindingHash: h("4e082afc18d2c5e8b1a4f7d0c3e6b9d2"),
    createdAt: iso(-9 * MIN),
    agent: "ops-agent",
    requestedBy: "Ops",
    request: {
      action: "infra.db.rotate-credentials",
      parametersSnapshot: {
        host: "aurora-bookings-db.replica.sg",
        engine: "postgres 15",
        rotation: "read-replica only",
        downtimeEstimate: "0s",
        rollbackPlan: "stored-snapshot 12h",
      },
      approvers: ["p-1", "kira.l"],
      approvalsRequired: 2,
    },
    state: { approvalHashes: ["0xK1RA"], respondedBy: null, respondedAt: null },
  },
  {
    id: "apr_55ab10",
    summary: "Charge no-show fee SGD 80 to client #SG-9221 (CoolSculpting 2026-05-12)",
    riskCategory: "low",
    status: "pending",
    envelopeId: "env_55ab10d2",
    expiresAt: iso(2 * HR),
    bindingHash: h("55ab10d2e7f4a1c8b5e2a9d6c3f0b7e4"),
    createdAt: iso(-4 * MIN),
    agent: "billing-agent",
    requestedBy: "Billing",
    request: {
      action: "billing.fee.apply",
      parametersSnapshot: {
        clientId: "SG-9221",
        appointmentId: "appt_88412",
        amount: 80,
        currency: "SGD",
        reason: "no_show_under_24h",
        policy: "cancellation.v3",
      },
      approvers: ["p-1"],
      approvalsRequired: 1,
    },
    state: { approvalHashes: [], respondedBy: null, respondedAt: null },
  },
  {
    id: "apr_a44f02",
    summary: "Update IPL Hair Removal package prices · +12% across 6 tiers",
    riskCategory: "medium",
    status: "pending",
    envelopeId: "env_a44f02b5",
    expiresAt: iso(5 * HR + 22 * MIN),
    bindingHash: h("a44f02b5d8e1c4f7a0c3e6b9d2f5a8c1"),
    createdAt: iso(-12 * MIN),
    agent: "ad-optimizer",
    requestedBy: "Growth",
    request: {
      action: "catalog.price.update",
      parametersSnapshot: {
        catalog: "ipl_hair_removal_2026",
        tiersAffected: 6,
        adjustmentPct: 12,
        effectiveAt: "2026-05-15T00:00:00+08:00",
        rationale: "Q2 cost-pass-through; matches reference set in S2 review",
      },
      approvers: ["p-1"],
      approvalsRequired: 1,
    },
    state: { approvalHashes: [], respondedBy: null, respondedAt: null },
  },
  {
    id: "apr_19fe44",
    summary: "Reschedule 14 appointments after laser tech sick-leave (Wed 14 May)",
    riskCategory: "low",
    status: "pending",
    envelopeId: "env_19fe44a7",
    expiresAt: iso(6 * HR),
    bindingHash: h("19fe44a7c2e5b8d1f4c7e0a3b6d9c2f5"),
    createdAt: iso(-88 * MIN),
    agent: "bookings-agent",
    requestedBy: "Bookings",
    request: {
      action: "calendar.reschedule.bulk",
      parametersSnapshot: {
        count: 14,
        fromDate: "2026-05-14",
        windowSearch: "next_4_business_days",
        notify: "sms+email",
        notifyTemplate: "tech_unavailable_v2",
      },
      approvers: ["p-1"],
      approvalsRequired: 1,
    },
    state: { approvalHashes: [], respondedBy: null, respondedAt: null },
  },
  {
    id: "apr_c81b33",
    summary: "Purge 4,210 inactive guest sessions older than 30d (PDPA retention)",
    riskCategory: "high",
    status: "pending",
    envelopeId: "env_c81b33f6",
    expiresAt: iso(90 * MIN),
    bindingHash: h("c81b33f6a9d2c5e8b1a4f7d0c3e6b9d2"),
    createdAt: iso(-33 * MIN),
    agent: "data-agent",
    requestedBy: "Ops",
    request: {
      action: "data.session.purge",
      parametersSnapshot: {
        rows: 4210,
        table: "session_guest_v2",
        oldestRow: "2026-03-30",
        backupAvailable: false,
        reversible: false,
      },
      approvers: ["p-1"],
      approvalsRequired: 1,
    },
    state: { approvalHashes: [], respondedBy: null, respondedAt: null },
  },
  {
    id: "apr_2e9bd1",
    summary: "Issue SGD 500 service voucher · client #SG-77104 (post-treatment complaint)",
    riskCategory: "medium",
    status: "pending",
    envelopeId: "env_2e9bd14c",
    expiresAt: iso(18 * HR),
    bindingHash: h("2e9bd14c7a0d3f6b9e2c5a8d1f4c7e0a"),
    createdAt: iso(-4 * HR),
    agent: "support-agent",
    requestedBy: "Care",
    request: {
      action: "billing.voucher.issue",
      parametersSnapshot: {
        clientId: "SG-77104",
        amount: 500,
        currency: "SGD",
        expiresDays: 180,
        memo: "Goodwill voucher per Care escalation #ESC-3318",
      },
      approvers: ["p-1"],
      approvalsRequired: 1,
    },
    state: { approvalHashes: [], respondedBy: null, respondedAt: null },
  },
  {
    id: "apr_f01a99",
    summary: "Scale daily ad budget · Cleaning treatments · +20%",
    riskCategory: "low",
    status: "pending",
    envelopeId: "env_f01a99e2",
    expiresAt: iso(3 * HR),
    bindingHash: h("f01a99e2b5c8d1f4a7c0e3b6d9c2f5a8"),
    createdAt: iso(-2 * HR),
    agent: "ad-optimizer",
    requestedBy: "Growth",
    request: {
      action: "ads.budget.scale",
      parametersSnapshot: {
        adset: "Cleaning · retarget · 30d",
        currentBudget: "SGD 200/day",
        proposedBudget: "SGD 240/day",
        guardrail: "+25% max",
        roas7d: 4.1,
      },
      approvers: ["p-1"],
      approvalsRequired: 1,
    },
    state: { approvalHashes: [], respondedBy: null, respondedAt: null },
  },
  {
    id: "apr_b21d7f",
    summary: "Push updated PDPA consent form (v4) to all booking flows",
    riskCategory: "high",
    status: "pending",
    envelopeId: "env_b21d7f4e",
    expiresAt: iso(90 * MIN),
    bindingHash: h("b21d7f4e8c1a5f2d7b3e6a9c2f5d8e1b"),
    createdAt: iso(-26 * MIN),
    agent: "compliance-agent",
    requestedBy: "Ops",
    request: {
      action: "cms.consent.publish",
      parametersSnapshot: {
        documentId: "pdpa_consent_v4",
        replaces: "pdpa_consent_v3",
        effectiveAt: "immediate",
        surfaces: ["web", "ios", "android", "kiosk"],
        legalReviewer: "S. Lim (Counsel)",
      },
      approvers: ["p-1", "kira.l"],
      approvalsRequired: 2,
    },
    state: { approvalHashes: [], respondedBy: null, respondedAt: null },
  },
  {
    id: "apr_e0c4a5",
    summary: "Run GDPR/PDPA data export · subject sarah.k@example.com",
    riskCategory: "medium",
    status: "recovery_required",
    envelopeId: "env_e0c4a5d1",
    expiresAt: iso(18 * HR),
    bindingHash: h("e0c4a5d1b8e3a6c9f2d5b8e1a4d7c0e3"),
    createdAt: iso(-6 * HR),
    agent: "compliance-agent",
    requestedBy: "Ops",
    request: {
      action: "compliance.gdpr.export",
      parametersSnapshot: {
        subject: "sarah.k@example.com",
        deliverBy: "2026-05-18",
        format: "json+csv bundle",
        scope: ["orders", "sessions", "support_threads", "treatment_notes"],
      },
      approvers: ["p-1"],
      approvalsRequired: 1,
    },
    recovery: {
      reason:
        "Upstream cartridge `compliance-export@1.4.2` returned 502 during dry-run binding capture.",
      proposedFix:
        "Re-run the binding capture; lifecycle will be re-instantiated with a fresh parametersSnapshot.",
      lastAttemptAt: iso(-11 * MIN),
    },
    state: { approvalHashes: [], respondedBy: null, respondedAt: null },
  },
];
