// ---------------------------------------------------------------------------
// Email Channel — Prepares email payloads without an SMTP dependency
// ---------------------------------------------------------------------------
// This adapter constructs a "prepared email" object that the orchestrator
// layer can hand off to an actual SMTP transport. It does NOT send the
// email itself — there is no nodemailer / SMTP library in this package.
// ---------------------------------------------------------------------------

import type {
  EmailChannelConfig,
  NotificationPayload,
  NotificationResult,
} from "../types.js";

/**
 * Represents a fully constructed email ready for delivery by an
 * external transport (e.g. nodemailer, AWS SES, SendGrid).
 */
export interface PreparedEmail {
  from: string;
  to: string[];
  subject: string;
  textBody: string;
  smtpHost: string;
  smtpPort: number;
  useTls: boolean;
  auth?: { user: string; pass: string };
}

export class EmailChannel {
  /** The most recently prepared email — exposed for testability. */
  lastPreparedEmail: PreparedEmail | null = null;

  constructor(private readonly config: EmailChannelConfig) {}

  /**
   * Build a prepared email payload from the notification.
   * Returns a successful NotificationResult with the prepared email
   * stored on `this.lastPreparedEmail`.
   *
   * Since there is no SMTP transport, this always succeeds unless the
   * config is invalid.
   */
  async send(payload: NotificationPayload): Promise<NotificationResult> {
    try {
      const subject = this.buildSubject(payload);
      const textBody = this.buildTextBody(payload);

      this.lastPreparedEmail = {
        from: this.config.from,
        to: this.config.to,
        subject,
        textBody,
        smtpHost: this.config.smtpHost,
        smtpPort: this.config.smtpPort,
        useTls: this.config.useTls ?? true,
        auth: this.config.auth,
      };

      return {
        channelType: "email",
        success: true,
      };
    } catch (err) {
      return {
        channelType: "email",
        success: false,
        error: err instanceof Error ? err.message : String(err),
      };
    }
  }

  /**
   * Returns the most recently prepared email, or null if `send` has not
   * been called yet.
   */
  getPreparedEmail(): PreparedEmail | null {
    return this.lastPreparedEmail;
  }

  // ---------------------------------------------------------------------------
  // Private helpers
  // ---------------------------------------------------------------------------

  private buildSubject(payload: NotificationPayload): string {
    const tag = payload.severity === "critical"
      ? "[CRITICAL]"
      : payload.severity === "warning"
        ? "[WARNING]"
        : "[INFO]";

    return `${tag} ${payload.title} — Account ${payload.accountId}`;
  }

  private buildTextBody(payload: NotificationPayload): string {
    const lines: string[] = [
      `Alert: ${payload.title}`,
      `Severity: ${payload.severity.toUpperCase()}`,
      `Alert Type: ${payload.alertType}`,
      `Account: ${payload.accountId}`,
      `Time: ${payload.timestamp}`,
      "",
      payload.message,
      "",
    ];

    const detailEntries = Object.entries(payload.details);
    if (detailEntries.length > 0) {
      lines.push("Details:");
      lines.push("-".repeat(40));
      for (const [key, value] of detailEntries) {
        lines.push(`  ${key}: ${String(value)}`);
      }
      lines.push("");
    }

    lines.push("-".repeat(40));
    lines.push("This alert was generated by Switchboard Digital Ads.");

    return lines.join("\n");
  }
}
