import type { ScheduledTriggersListResponse } from "@switchboard/schemas";

export const AUTOMATIONS_FIXTURE_PAGE: ScheduledTriggersListResponse = {
  rows: [
    {
      id: "fix-cron-active",
      type: "cron",
      status: "active",
      scheduleLabel: "0 7 * * *",
      actionType: "spawn_workflow",
      sourceWorkflowId: "a1b2c3d4-aaaa-bbbb-cccc-dddddddddddd",
      createdAt: "2026-05-07T09:00:00.000Z",
      fireAt: null,
      expiresAt: null,
      drawer: {
        eventPatternSummary: null,
        visibleActionPayloadKeys: ["workflowId", "agentKey"],
        redactedKeyCount: 0,
      },
    },
    {
      id: "fix-timer-active",
      type: "timer",
      status: "active",
      scheduleLabel: "2026-05-12T18:00:00.000Z",
      actionType: "emit_event",
      sourceWorkflowId: null,
      createdAt: "2026-05-08T14:30:00.000Z",
      fireAt: "2026-05-12T18:00:00.000Z",
      expiresAt: null,
      drawer: {
        eventPatternSummary: null,
        visibleActionPayloadKeys: ["eventType", "contactId"],
        redactedKeyCount: 1,
      },
    },
    {
      id: "fix-event-active",
      type: "event_match",
      status: "active",
      scheduleLabel: "event:lead.captured",
      actionType: "spawn_workflow",
      sourceWorkflowId: "e5f6g7h8-eeee-ffff-gggg-hhhhhhhhhhhh",
      createdAt: "2026-05-08T16:15:00.000Z",
      fireAt: null,
      expiresAt: null,
      drawer: {
        eventPatternSummary: "lead.captured (filters: source, contactId)",
        visibleActionPayloadKeys: ["workflowId"],
        redactedKeyCount: 0,
      },
    },
    {
      id: "fix-cron-fired",
      type: "cron",
      status: "fired",
      scheduleLabel: "*/15 * * * *",
      actionType: "resume_workflow",
      sourceWorkflowId: "i9j0k1l2-iiii-jjjj-kkkk-llllllllllll",
      createdAt: "2026-04-30T12:00:00.000Z",
      fireAt: null,
      expiresAt: null,
      drawer: {
        eventPatternSummary: null,
        visibleActionPayloadKeys: ["workflowId"],
        redactedKeyCount: 0,
      },
    },
    {
      id: "fix-timer-cancelled",
      type: "timer",
      status: "cancelled",
      scheduleLabel: "2026-05-04T10:00:00.000Z",
      actionType: "spawn_workflow",
      sourceWorkflowId: null,
      createdAt: "2026-05-02T08:00:00.000Z",
      fireAt: "2026-05-04T10:00:00.000Z",
      expiresAt: null,
      drawer: {
        eventPatternSummary: null,
        visibleActionPayloadKeys: ["workflowId", "contactId"],
        redactedKeyCount: 0,
      },
    },
    {
      id: "fix-cron-expired",
      type: "cron",
      status: "expired",
      scheduleLabel: "0 0 1 * *",
      actionType: "emit_event",
      sourceWorkflowId: null,
      createdAt: "2026-03-01T00:00:00.000Z",
      fireAt: null,
      expiresAt: "2026-04-01T00:00:00.000Z",
      drawer: {
        eventPatternSummary: null,
        visibleActionPayloadKeys: ["eventType"],
        redactedKeyCount: 0,
      },
    },
  ],
  statusCounts: { all: 6, active: 3, fired: 1, cancelled: 1, expired: 1 },
  nextCursor: null,
  hasMore: false,
};
